---
- name: 'Prepare an Ansible host for GitHub Actions'
  hosts: localhost
  tasks:
    - name: 'Install tar for tasks delegated to the localhost'
      community.general.apk:
        name: 'tar'
        update_cache: true
      when: ansible_os_family == 'Alpine'

- name: 'Install the Postgres Exporter'
  hosts: all
  roles:
    - role: antmelekhin.postgres_exporter
