---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check if Postgres Exporter is installed'
      ansible.builtin.stat:
        path: '/usr/local/bin/postgres_exporter'
      register: __postgres_exporter_is_installed
      failed_when: __postgres_exporter_is_installed['stat']['exists'] | bool
      check_mode: true

    - name: 'Check if Postgres Exporter service is running'
      ansible.builtin.systemd:
        name: 'postgres_exporter'
        state: 'started'
        enabled: true
      register: __postgres_exporter_service
      failed_when: __postgres_exporter_service is changed
      check_mode: true

    - name: 'Check web_config.yaml does not exist'
      ansible.builtin.stat:
        path: '/etc/postgres_exporter/web_config.yaml'
      register: __postgres_exporter_config
      failed_when: __postgres_exporter_config['stat']['exists'] | bool
      check_mode: true
