---
- name: 'Check current Postgres Exporter version'
  ansible.builtin.command:
    cmd: '{{ postgres_exporter_install_path }}/postgres_exporter --version'
  failed_when: false
  changed_when: false
  register: _postgres_exporter_version_check

- block:
    - name: 'Download Postgres Exporter binary to local folder'
      ansible.builtin.get_url:
        url: '{{ postgres_exporter_download_url }}'
        dest: '/tmp/{{ postgres_exporter_package_name }}.tar.gz'
        mode: 0644
      delegate_to: localhost
      check_mode: false

    - name: 'Unarchive Postgres Exporter binary'
      ansible.builtin.unarchive:
        src: '/tmp/{{ postgres_exporter_package_name }}.tar.gz'
        dest: '/tmp'
        creates: '/tmp/{{ postgres_exporter_package_name }}/postgres_exporter'
      delegate_to: localhost
      check_mode: false

    - name: 'Copy Postgres Exporter binary into place'
      ansible.builtin.copy:
        src: '/tmp/{{ postgres_exporter_package_name }}/postgres_exporter'
        dest: '{{ postgres_exporter_install_path }}/postgres_exporter'
        owner: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        mode: 0755
      notify: Restart Postgres Exporter
      when: not ansible_check_mode
      become: true
  when:
    - _postgres_exporter_version_check.stdout is not defined or
      postgres_exporter_version not in _postgres_exporter_version_check.stdout
