---
- name: 'Prepare for installing the Postgres Exporter'
  ansible.builtin.include_tasks: '{{ ansible_system }}/pre-install.yml'

- name: 'Install the Postgres Exporter'
  ansible.builtin.include_tasks: '{{ ansible_system }}/install.yml'

- name: 'Configure the Postgres Exporter'
  ansible.builtin.include_tasks: '{{ ansible_system }}/configure.yml'
