---
- name: 'Include tasks for preparing to install Postgres Exporter'
  ansible.builtin.import_tasks: 'pre-install.yml'

- name: 'Include tasks for install Postgres Exporter'
  ansible.builtin.import_tasks: 'install.yml'

- name: 'Include tasks for configure Postgres Exporter'
  ansible.builtin.import_tasks: 'configure.yml'
