---
- name: 'Prepare for installing the Postgres Exporter'
  ansible.builtin.include_tasks: "{{ ansible_facts['system'] }}/pre-install.yml"

- name: 'Install the Postgres Exporter'
  ansible.builtin.include_tasks: "{{ ansible_facts['system'] }}/install.yml"

- name: 'Configure the Postgres Exporter'
  ansible.builtin.include_tasks: "{{ ansible_facts['system'] }}/configure.yml"
