---
- name: 'Linux | Restart the Postgres Exporter'
  become: true
  ansible.builtin.systemd:
    name: 'postgres_exporter'
    daemon_reload: true
    state: 'restarted'
  when: not ansible_check_mode

- name: 'Linux | Systemd daemon-reload'
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: not ansible_check_mode

- name: 'Windows | Restart the Postgres Exporter scheduled task'
  ansible.windows.win_shell: schtasks /end /tn 'Postgres Exporter'; schtasks /run /tn 'Postgres Exporter'
