---
- name: 'Converge'
  hosts: all
  vars:
    postgres_exporter_tls_server_config:
      cert_file: '/usr/local/etc/ssl/postgres_exporter.cert'
      key_file: '/usr/local/etc/ssl/postgres_exporter.key'
    postgres_exporter_basic_auth_users:
      newuser1: 'newpassword1'

  pre_tasks:
    - name: 'Create a certificate directory'
      ansible.builtin.file:
        path: '{{ postgres_exporter_tls_server_config.cert_file | dirname }}'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: 0755

    - name: 'Copy the certificate and key'
      ansible.builtin.copy:
        src: '{{ cert.src }}'
        dest: '{{ cert.dest }}'
        mode: 0644
      loop:
        - src: '/tmp/certificate.cert'
          dest: '{{ postgres_exporter_tls_server_config.cert_file }}'
        - src: '/tmp/certificate.key'
          dest: '{{ postgres_exporter_tls_server_config.key_file }}'
      loop_control:
        loop_var: cert

  roles:
    - role: antmelekhin.postgres_exporter
