---
- name: Converge
  hosts: all

  pre_tasks:
    - name: 'Update APT cache'
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.postgresql
      postgresql_users:
        - name: 'molecule'
          password: 'molecule'
          role_attr_flags: SUPERUSER
      postgresql_databases:
        - name: 'molecule'
          lc_collate: 'en_US.UTF-8'
          lc_ctype: 'en_US.UTF-8'
          encoding: 'UTF-8'
          template: 'template0'
          owner: 'molecule'

    - role: antmelekhin.postgres_exporter
