---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: ubuntu-2004
    image: jrei/systemd-ubuntu:20.04
    published_ports:
      - 0.0.0.0:9187:9187/udp
      - 0.0.0.0:9187:9187/tcp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
verifier:
  name: ansible
