---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that Postgres Exporter service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['postgres_exporter.service'].state == 'running'
          - ansible_facts.services['postgres_exporter.service'].status == 'enabled'

    - name: 'Verify the Postgres Exporter is responding to requests'
      ansible.builtin.uri:
        url: 'http://{{ ansible_host }}:9187/metrics'
      register: __postgres_exporter_response
      until: __postgres_exporter_response.status == 200
      retries: 120
      delay: 5

    - name: 'Check the current Postgres Exporter version'
      ansible.builtin.command:
        cmd: '/usr/local/bin/postgres_exporter --version'
      failed_when: false
      changed_when: false
      register: __postgres_exporter_version_check

    - name: 'The Postgres Exporter version output'
      ansible.builtin.debug:
        msg: 'The current Postgres Exporter version is {{ __postgres_exporter_version_check.stderr_lines[0].split()[2] }}'
