---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Verify the Postgres Exporter is responding to requests'
      ansible.builtin.uri:
        url: 'http://{{ ansible_host }}:9187/metrics'
      delegate_to: localhost
      register: __postgres_exporter_response
      until: __postgres_exporter_response.status == 200
      retries: 120
      delay: 5

    - name: 'Check the current Postgres Exporter version'
      ansible.windows.win_command:
        cmd: '"C:\Program Files\postgres_exporter\postgres_exporter.exe" --version'
      failed_when: false
      changed_when: false
      register: __postgres_exporter_version_check

    - name: 'The Postgres Exporter version output'
      ansible.builtin.debug:
        msg: 'The current Postgres Exporter version is {{ __postgres_exporter_version_check.stderr_lines[0].split()[2] }}'
