---
- name: 'Configure and start Postgres Exporter'
  become: true
  block:
    - name: 'Linux | Configure SystemD unit for Postgres Exporter'
      ansible.builtin.template:
        src: 'postgres_exporter.service.j2'
        dest: '/etc/systemd/system/postgres_exporter.service'
        owner: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        mode: 0644
      notify: Linux | Restart Postgres Exporter

    - name: 'Linux | Ensure Postgres Exporter is running and enabled at boot'
      ansible.builtin.systemd:
        name: postgres_exporter
        state: started
        enabled: true
