---
- name: 'Linux | Configure and start the Postgres Exporter'
  become: true
  block:
    - name: 'Linux | Copy the Postgres Exporter systemd service'
      ansible.builtin.template:
        src: 'postgres_exporter.service.j2'
        dest: '/etc/systemd/system/postgres_exporter.service'
        owner: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        mode: 0644
      notify: 'Linux | Restart the Postgres Exporter'

    - name: 'Linux | Copy the Postgres Exporter web configuration file'
      ansible.builtin.template:
        src: 'web_config.yaml.j2'
        dest: '{{ postgres_exporter_config_path }}/web_config.yaml'
        owner: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        mode: 0600
      notify: 'Linux | Restart the Postgres Exporter'
      when:
        - postgres_exporter_tls_server_config | length or
          postgres_exporter_http_server_config | length or
          postgres_exporter_basic_auth_users | length

    - name: 'Linux | Ensure the Postgres Exporter is running and enabled at boot'
      ansible.builtin.systemd:
        name: 'postgres_exporter'
        state: 'started'
        enabled: true
      when: not ansible_check_mode

- name: 'Linux | Configure SELinux when is already installed'
  when: ansible_selinux.status == 'enabled'
  become: true
  block:
    - name: 'Linux | Install the required SELinux packages'
      ansible.builtin.package:
        name: "{{ ['policycoreutils-python']
          if ansible_python_version is version('3', '<')
          else ['policycoreutils-python-utils'] }}"
        state: 'present'

    - name: 'Linux | Allow the Postgres Exporter port in SELinux'
      community.general.seport:
        ports: '{{ postgres_exporter_web_listen_port }}'
        proto: 'tcp'
        setype: 'http_port_t'
        state: 'present'
