---
- name: 'Prepare to install the Postgres Exporter'
  when: postgres_exporter_user != 'postgres'
  become: true
  block:
    - name: 'Linux | Create a Postgres Exporter group'
      ansible.builtin.group:
        name: '{{ postgres_exporter_group }}'
        system: true

    - name: 'Linux | Create a Postgres Exporter user'
      ansible.builtin.user:
        name: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        comment: 'Postgres Exporter'
        system: true
        createhome: false
        shell: '/bin/false'
