---
- name: 'Linux | Prepare for installing the Postgres Exporter'
  become: true
  block:
    - name: 'Linux | Create a Postgres Exporter group'
      ansible.builtin.group:
        name: '{{ postgres_exporter_group }}'
        system: true
      when: postgres_exporter_group != 'postgres'

    - name: 'Linux | Create a Postgres Exporter user'
      ansible.builtin.user:
        name: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        comment: 'Postgres Exporter'
        system: true
        createhome: false
        shell: '/bin/false'
      when: postgres_exporter_user != 'postgres'

    - name: 'Linux | Create a Postgres Exporter configuration directory'
      ansible.builtin.file:
        path: '{{ postgres_exporter_config_path }}'
        owner: '{{ postgres_exporter_user }}'
        group: '{{ postgres_exporter_group }}'
        state: 'directory'
        mode: 0755
