---
- name: 'Linux | Uninstall the Postgres Exporter'
  become: true
  block:
    - name: 'Linux | Check if Postgres Exporter systemd service is existed'
      ansible.builtin.stat:
        path: '/etc/systemd/system/postgres_exporter.service'
      register: __postgres_exporter_unit_file

    - name: 'Linux | Ensure the Postgres Exporter is stopped and disabled at boot'
      ansible.builtin.systemd:
        name: 'postgres_exporter'
        state: 'stopped'
        enabled: false
      when: __postgres_exporter_unit_file.stat.exists

    - name: 'Linux | Remove the Postgres Exporter systemd service'
      ansible.builtin.file:
        path: '/etc/systemd/system/postgres_exporter.service'
        state: 'absent'
      notify: 'Linux | Systemd daemon-reload'

    - name: 'Linux | Remove the Postgres Exporter binary'
      ansible.builtin.file:
        path: '{{ postgres_exporter_install_path }}/postgres_exporter'
        state: 'absent'

    - name: 'Linux | Remove a Postgres Exporter configuration directory'
      ansible.builtin.file:
        path: '{{ postgres_exporter_config_path }}'
        state: 'absent'

    - name: 'Linux | Remove a Postgres Exporter user'
      ansible.builtin.user:
        name: '{{ postgres_exporter_user }}'
        state: 'absent'
        remove: true

    - name: 'Linux | Remove a Postgres Exporter group'
      ansible.builtin.group:
        name: '{{ postgres_exporter_group }}'
        state: 'absent'
