---
- name: 'Windows | Set an environment variable for Postgres Exporter'
  win_environment:
    level: machine
    name: 'DATA_SOURCE_NAME'
    value: '{{ postgres_exporter_data_source_name }}'
    state: present

- name: 'Windows | Configure startup script for Postgres Exporter'
  win_template:
    src: 'Start-PostgresExporter.ps1.j2'
    dest: '{{ postgres_exporter_install_path }}\Start-PostgresExporter.ps1'
  register: _postgres_exporter_startup_script

- name: 'Windows | Configure web config file for Postgres Exporter'
  win_template:
    src: 'web_config.yaml.j2'
    dest: '{{ postgres_exporter_config_path }}\web_config.yaml'
  register: _postgres_exporter_web_config
  when:
    - postgres_exporter_tls_server_config | length or
      postgres_exporter_http_server_config | length or
      postgres_exporter_basic_auth_users | length

- name: 'Windows | Ensure scheduled task for Postgres Exporter is enabled at boot'
  win_scheduled_task:
    name: 'Postgres Exporter'
    description: 'Prometheus exporter for Postgres server metrics.'
    actions:
      - path: '%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe'
        arguments: '-ExecutionPolicy ByPass -File "{{ postgres_exporter_install_path }}\Start-PostgresExporter.ps1"'
    triggers:
      - type: 'boot'
    execution_time_limit: 'PT0S'
    username: 'SYSTEM'
    enabled: true
    state: present
  register: _postgres_exporter_scheduled_task

- name: 'Windows | Ensure scheduled task for Postgres Exporter is running'
  win_shell: schtasks /end /tn 'Postgres Exporter'; schtasks /run /tn 'Postgres Exporter'
  when:
    - not ansible_check_mode
    - _postgres_exporter_startup_script is changed or
      _postgres_exporter_web_config is changed or
      _postgres_exporter_scheduled_task is changed

- name: 'Windows | Ensure firewall rule for Postgres Exporter is allow'
  win_firewall_rule:
    name: 'Postgres Exporter'
    description: 'Inbound rule for Postgres Exporter'
    program: '{{ postgres_exporter_install_path }}\postgres_exporter.exe'
    localport: '{{ postgres_exporter_web_listen_port }}'
    action: allow
    direction: in
    protocol: tcp
    profiles: 'domain,private,public'
    enabled: true
    state: present
