---
- name: 'Windows | Check current Postgres Exporter version'
  win_command:
    cmd: '{{ postgres_exporter_install_path }}/postgres_exporter --version'
  failed_when: false
  changed_when: false
  register: _postgres_exporter_version_check

- name: 'Windows | Download and unarchive Postgres Exporter'
  when:
    - _postgres_exporter_version_check.stdout is not defined or
      postgres_exporter_version not in _postgres_exporter_version_check.stdout
  block:
    - name: 'Windows | Download Postgres Exporter binary to local folder'
      ansible.builtin.get_url:
        url: '{{ postgres_exporter_download_url }}/{{ _postgres_exporter_archive }}'
        dest: '/tmp/{{ _postgres_exporter_archive }}'
        mode: 0644
      delegate_to: localhost
      check_mode: false

    - name: 'Windows | Unarchive Postgres Exporter binary'
      ansible.builtin.unarchive:
        src: '/tmp/{{ _postgres_exporter_archive }}'
        dest: '/tmp'
        creates: '/tmp/{{ _postgres_exporter_tmp_dir }}/postgres_exporter.exe'
      delegate_to: localhost
      check_mode: false

    - name: 'Windows | Copy Postgres Exporter binary into place'
      win_copy:
        src: '/tmp/{{ _postgres_exporter_tmp_dir }}/postgres_exporter.exe'
        dest: '{{ postgres_exporter_install_path }}\postgres_exporter.exe'
      when: not ansible_check_mode
