---
- name: 'Windows | Check if Postgres Exporter is installed'
  ansible.windows.win_stat:
    path: '{{ postgres_exporter_install_path }}\postgres_exporter.exe'
  register: __postgres_exporter_is_installed

- name: 'Windows | Check the current Postgres Exporter version'
  ansible.windows.win_command:
    cmd: '"{{ postgres_exporter_install_path }}\postgres_exporter.exe" --version'
  failed_when: false
  changed_when: false
  register: __postgres_exporter_version_check

- name: 'Windows | Download and unarchive the Postgres Exporter'
  when:
    - not __postgres_exporter_is_installed.stat.exists or
      ( __postgres_exporter_version_check.stderr_lines | length and
      postgres_exporter_version not in __postgres_exporter_version_check.stderr_lines[0].split()[2] ) or
      ( __postgres_exporter_version_check.stdout_lines | length and
      postgres_exporter_version not in __postgres_exporter_version_check.stdout_lines[0].split()[2] )
  block:
    - name: 'Windows | Download the Postgres Exporter archive to a local folder'
      become: false
      ansible.builtin.get_url:
        url: '{{ postgres_exporter_download_url }}/{{ postgres_exporter_archive_name }}.tar.gz'
        dest: '{{ postgres_exporter_download_path }}/{{ postgres_exporter_archive_name }}.tar.gz'
        checksum: 'sha256:{{ postgres_exporter_checksum_url }}'
        mode: 0644
      delegate_to: localhost
      check_mode: false

    - name: 'Windows | Unarchive the Postgres Exporter binary'
      become: false
      ansible.builtin.unarchive:
        src: '{{ postgres_exporter_download_path }}/{{ postgres_exporter_archive_name }}.tar.gz'
        dest: '{{ postgres_exporter_download_path }}'
        creates: '{{ postgres_exporter_download_path }}/{{ postgres_exporter_archive_name }}/postgres_exporter.exe'
      delegate_to: localhost
      check_mode: false

    - name: 'Windows | Copy the Postgres Exporter binary to a target host'
      ansible.windows.win_copy:
        src: '{{ postgres_exporter_download_path }}/{{ postgres_exporter_archive_name }}/postgres_exporter.exe'
        dest: '{{ postgres_exporter_install_path }}\postgres_exporter.exe'
      notify: 'Windows | Restart the Postgres Exporter scheduled task'
      when: not ansible_check_mode
